### ISSUE TITLE
HW stripped of HDMI IP requires u-boot env and extlinux/extlinux.conf whacking

### ISSUE THREAD

**Issue by eric7373** [01org/de10-nano-hardware#2]
Problem: HDMI IP costs $$ in addition to Quartus standard edition license.  If the HW is built with the HDMI IP removed from the Qsys project (and its instantiation in top.v), it will only boot if the bootcmd env. var is stripped of "run hdmi_init".  Furthermore, even if this is done an additional bug is exposed because of mapping of the DTB.  This bug must be worked-around by editing extlinux/extlinux.conf and adding "FDTDIR ../"

**Comment by dwesterg** [comment]
This issue is resolved in the upcoming release.  The current hardware release includes a version that requires no IP licenses.  The dipswitch on the board is used to determine which design to load.

--dalon
