### ISSUE TITLE
 HW stripped of HDMI IP hangs during linux boot

### ISSUE THREAD

**Issue by eric7373** [01org/de10-nano-hardware#3]
Even with the workarounds mentioned in issue "HW stripped of HDMI IP requires u-boot env and extlinux/extlinux.conf whacking", the Linux boot hangs.  Debugging the hang is aggravated by issue "Linux 'halt' doesn't - due to apparent u-boot watchdog" i.e. there's no stack crawl ala CONFIG_LOCKUP_DETECTOR and/or CONFIG_DETECT_HUNG_TASK.

Yeah, I know - it might not be a true hang - it might merely be a delay that would otherwise complete if it weren't for the the watchdog wakeup.  :-)

**Comment by dwesterg** [comment]
i believe this issue is resolved in an upcoming release.
