### ISSUE TITLE
sopc2dts for upstream

### ISSUE THREAD

**Issue by feddischson** [01org/de10-nano-hardware#5]
Hi,

this is more a question than a issue:

You have some patches for sopc2dts.
Have you already forwarded them to upstream (I guess it should go into https://github.com/wgoossens/sopc2dts)?

If not: do you think it would be good to have them in upstream?

I just came across this point when I tried to create an  dtb overlay based on a custom design.
The whole tooling seems to be a bit scrappy. 

I was also wondering what kind of version of `sopc2dts` Intel is  shipping with it's tools? Is it a branch of https://github.com/wgoossens/sopc2dts?

**Comment by dwesterg** [comment]
Yes, this tool is just walter's sopc2dts.  No I never forwarded this patch set as it will not work under all circumstances, furthermore, sopc2dts has really not been all that maintainable and our reference designs are trending back towards traditionally created dts files.

see 

https://rocketboards.org/foswiki/Documentation/HOWTOCreateADeviceTree

--dalon

**Comment by feddischson** [comment]
ok, thanks for this info
